In [2]:
import numpy as np

x=np.array([1, 2, 3, 4])
x.shape

(4,)

In [14]:
def convert_dtype(arr, dtype):
    try:
        arr = np.array(arr, dtype=dtype)
        return arr.astype(dtype)
    except ValueError as e:
        raise ValueError(f"invalid target data type: {dtype}. Details: {e}")
    except TypeError as e:
            raise TypeError(f"invalid target data type: {dtype}. Details: {e}")
    

    

In [17]:
lst = [1, 2, 3, 4]
convert_dtype(lst, float)
 


array([1., 2., 3., 4.])

In [19]:
def check_dtype(arr, dtype):
    
    if not isinstance(arr, np.ndarray):
        raise TypeError("Input must be a numpy array.")
        
    dtype = np.dtype(dtype)
    return arr.dtype == dtype   
 

In [22]:
lst = [1, 2, 3, 4]
convert_dtype(lst, float)

array([1., 2., 3., 4.])

In [39]:
mat =np.zeros((3, 4))
print(mat.shape)
print(mat)
matrix=np.ones((3, 4))
print(matrix)

matrix1=np.full((3, 4), 7)
matrix1

(3, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [40]:
def init_array(shape, value=0):
    return np.full(shape, value)

In [45]:
zeros = init_array((3, 4))
print(zeros)

ones = init_array((3, 4), 1)
print(ones)

seven = init_array((3, 4), 7)
print(seven)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [64]:
def init_weights(n_feature, method = "zeros", seed =None): # lw sora msln kol pixel have weght 
    if not isinstance(n_feature, int):
        raise TypeError("n_feature must be an integer.")
    if n_feature <= 0:
        raise ValueError("n_feature must be a positive integer.")
    if method=="zeros":
        return np.zeros(n_feature)
    if method=="randoms":
        if seed is not None:
            np.random.seed(seed)
        return np.random.rand(n_feature)*0.01
    raise ValueError(f"un supported method: {method}. Supported methods are 'zeros' and 'randoms'.")
      

In [63]:
init_weights(5,"randoms")

array([9.46986724e-08, 8.27990728e-08, 4.54709008e-08, 4.74198441e-08,
       5.64762007e-08])

In [67]:
I = np.identity(5,dtype=int)
I


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [68]:
np.random.random((5,5))

array([[0.69001958, 0.47904083, 0.98287346, 0.342332  , 0.18775458],
       [0.13883153, 0.33856939, 0.42395857, 0.30669304, 0.42342859],
       [0.25089264, 0.65579213, 0.19555001, 0.54055556, 0.0581561 ],
       [0.82671249, 0.31813108, 0.35315204, 0.95227821, 0.00408711],
       [0.9660105 , 0.06362574, 0.27491952, 0.2788375 , 0.12284982]])

In [69]:
np.random.randint(1, 10, size=(3, 4))

array([[1, 1, 5, 5],
       [1, 5, 9, 7],
       [8, 2, 3, 1]], dtype=int32)

In [70]:
a = ["osama", "ahmed", "ali"]
np.random.choice(a, size=(3, 3))

array([['ali', 'osama', 'ahmed'],
       ['ahmed', 'ahmed', 'ahmed'],
       ['osama', 'osama', 'osama']], dtype='<U5')

In [72]:
mat1 = np.ones((3, 4))
mat2 = np.zeros((3, 4))

np.savez('file_da.npz', ones_mat = mat1, zeros_mat = mat2)



In [73]:
with np.load('file_da.npz') as file:
    mat1 = file['ones_mat']
    mat2 = file['zeros_mat']    
    print(mat1)
    print(mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [74]:
m1 = np.array([[1,2,3],
                   [4,5,6]])
m2 = np.array([[4,5,6],
                   [1,1,1]])

In [ ]:
new_mat = np.vstack((m1, m2)) # add samples vertically
new_mat

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [1, 1, 1]])

In [ ]:
new_mat = np.hstack((m1, m2)) # add features horizontally
new_mat

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 1, 1, 1]])

In [80]:
v = np.array([1, 2, 3,0])
np.all(v >= 1)

np.False_

In [85]:
# how chatgbt works as a machine learning model with a vector of weights and a vector of inputs, it calculates the output by performing a dot product between the two vectors. The output is then passed through an activation function to produce the final result.
v1 = np.array([1, 2, 3, 4]) #vector 1 

v2 = np.array([2, 4, 5, 3]) #vector 2
np.isclose(v1, v2, atol=1)

array([ True, False, False,  True])

In [84]:
# how chatgbt works as a machine learning model with a vector of weights and a vector of inputs, it calculates the output by performing a dot product between the two vectors. The output is then passed through an activation function to produce the final result.
v1 = np.array([1, 2, 3, 4]) #vector 1 

v2 = np.array([2, 4, 5, 3]) #vector 2
np.allclose(v1, v2, atol=1)

False

In [ ]:
v = np.array([1, 2, 3])
condition = (v > 1) & (v < 3)
print (condition)
v[condition] = -1 # aly by match hy7to b -1 bnst5dmo fe 7l al exploding
print(v)

[False  True False]
[ 1 -1  3]


In [90]:
v = np.array([1, 2, 3])
condition = (v > 1) & (v < 3)
print (condition)
new_arr= np.where(condition, -1, v) # aly by match hy7to b -1 bnst5dmo fe 7l al exploding
print(new_arr)

[False  True False]
[ 1 -1  3]


In [91]:
v1 = np.array([1, 2, 3, 4])
c= 2
summation = v1 + c
multiplication = v1 * c
print("Summation:", summation)
print("Multiplication:", multiplication)


Summation: [3 4 5 6]
Multiplication: [2 4 6 8]


In [93]:
[[1,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0]]

[[1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]