In [2]:
import numpy as np

def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == 'zeros':
        return np.zeros(shape)
    elif mode == 'ones':
        return np.ones(shape)
    elif mode == 'full':
        return np.full(shape, value)
    elif mode == 'identity':
        # If shape is passed as an integer n or a tuple (n, n), extract the scalar dimension
        n = shape if isinstance(shape, int) else shape[0]
        return np.eye(n)
    else:
        raise ValueError(f"Unknown mode: {mode}")

In [6]:
print(array_factory('zeros', (3, 4)))

print(array_factory('ones', (2, 5)))
print(array_factory('full', (3, 3), value=7))
print(array_factory('identity', (3, 3)))
print(array_factory('icon', 4))  # This will create a 4x4 identity matrix

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


ValueError: Unknown mode: icon

In [7]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Step 1: Convert inputs to ndarray
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        # Step 2: Change the shape of arr1 to new_shape
        reshaped_arr1 = arr1.reshape(new_shape)

        # Step 3: Rule: Vertical Stacking (vstack)
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack((reshaped_arr1, arr2))

        return combined_dataset

    except ValueError as e:
        # Catch incompatible reshape sizes or mismatched column counts during vstack
        raise ValueError(f"Company-grade Error: {e}")

In [13]:
print(secure_reshape_and_stack([[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10]], (3, 2)))
print(secure_reshape_and_stack([[1, 2], [3, 4]], [[5, 6], [7, 8]], (2, 2)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
